import type { Product } from './productTypes.ts';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Màn hình Dell UltraSharp U2723QE 4K IPS Black',
    price: 13990000,
    originalPrice: 15500000,
    category: 'Màn hình',
    description: 'Màn hình đồ họa chuẩn mực 27 inch 4K, công nghệ IPS Black tương phản 2000:1, tích hợp Hub Type-C 90W sạc laptop.',
    specs: ['27" 4K UHD 3840x2160', 'IPS Black 2000:1', '98% DCI-P3', 'USB-C 90W Power Delivery'],
    stock: 14,
    rating: 4.9,
    reviewsCount: 128,
    imageColor: 'linear-gradient(135deg, #1e293b, #0f172a)',
    badge: 'Bán Chạy Nhất',
  },
  {
    id: 'prod-02',
    name: 'Bàn phím cơ Keychron Q1 Pro Wireless QMK/VIA',
    price: 4390000,
    originalPrice: 4890000,
    category: 'Bàn phím',
    description: 'Layout 75% Custom, khung nhôm CNC Anodized nguyên khối, Gasket Mount êm ái, kết nối Bluetooth 5.1 & Type-C tiện lợi.',
    specs: ['Nhôm CNC nguyên khối', 'Switch K Pro Red Hot-swap', 'South-facing RGB', 'Keycap PBT Double-shot'],
    stock: 8,
    rating: 4.8,
    reviewsCount: 94,
    imageColor: 'linear-gradient(135deg, #312e81, #1e1b4b)',
    badge: 'Hot Deal',
  },
  {
    id: 'prod-03',
    name: 'Chuột Logitech MX Master 3S Ergonomic Wireless',
    price: 2350000,
    originalPrice: 2690000,
    category: 'Chuột',
    description: 'Chuột công thái học hàng đầu cho lập trình viên và designer, Quiet Clicks giảm 90% tiếng ồn, cuộn MagSpeed 1000 dòng/giây.',
    specs: ['Cảm biến 8000 DPI Darkfield', 'Cuộn siêu tốc MagSpeed', 'Pin 70 ngày sạc nhanh', 'Logi Bolt & Bluetooth'],
    stock: 22,
    rating: 4.9,
    reviewsCount: 310,
    imageColor: 'linear-gradient(135deg, #14532d, #064e3b)',
    badge: 'Lựa Chọn Hàng Đầu',
  },
  {
    id: 'prod-04',
    name: 'Tai nghe Chống ồn Sony WH-1000XM5 Hi-Res Audio',
    price: 7490000,
    originalPrice: 8490000,
    category: 'Âm thanh',
    description: 'Công nghệ chống ồn chủ động hàng đầu thế giới với 2 bộ xử lý và 8 micro, màng loa 30mm sợi carbon mang lại âm thanh tuyệt hảo.',
    specs: ['Chống ồn thích ứng ANC', 'Driver sợi carbon 30mm', 'Hỗ trợ LDAC / DSEE Extreme', 'Pin 30h sạc nhanh'],
    stock: 11,
    rating: 4.8,
    reviewsCount: 86,
    imageColor: 'linear-gradient(135deg, #4c1d95, #2e1065)',
  },
  {
    id: 'prod-05',
    name: 'Giá đỡ màn hình Human Motion T6 Pro Công thái học',
    price: 1290000,
    originalPrice: 1450000,
    category: 'Phụ kiện',
    description: 'Tay đỡ màn hình trợ lực lò xo cơ học bền bỉ, chịu tải đến 9kg cho màn 17-32 inch, hỗ trợ quản lý dây cáp ngầm gọn gàng.',
    specs: ['Tải trọng tối đa 9kg', 'VESA 75x75, 100x100', 'Xoay 360°, ngửa ±90°', 'Kẹp bàn hoặc khoan lỗ'],
    stock: 35,
    rating: 4.7,
    reviewsCount: 204,
    imageColor: 'linear-gradient(135deg, #701a75, #4a044e)',
  },
  {
    id: 'prod-06',
    name: 'Đèn treo màn hình chống mỏi mắt Baseus i-wok 3',
    price: 690000,
    originalPrice: 850000,
    category: 'Phụ kiện',
    description: 'Chiếu sáng bất đối xứng không gây chói màn hình, cảm ứng điều chỉnh nhiệt độ màu 3000K - 6500K và độ sáng mượt mà.',
    specs: ['Ánh sáng bất đối xứng', 'CRI > 95 tái tạo màu', 'Cảm ứng vô cấp', 'Cấp nguồn qua cổng Type-C'],
    stock: 40,
    rating: 4.6,
    reviewsCount: 152,
    imageColor: 'linear-gradient(135deg, #831843, #500724)',
  },
  {
    id: 'prod-07',
    name: 'Bàn phím không dây Apple Magic Keyboard Touch ID',
    price: 3690000,
    originalPrice: 3990000,
    category: 'Bàn phím',
    description: 'Thiết kế siêu mỏng tối giản, tích hợp cảm biến Touch ID mở khóa máy và thanh toán an toàn cho hệ sinh thái Mac.',
    specs: ['Tích hợp Touch ID', 'Pin sạc tích hợp qua Type-C', 'Trọng lượng chỉ 243g', 'Tương thích Apple Silicon'],
    stock: 16,
    rating: 4.7,
    reviewsCount: 75,
    imageColor: 'linear-gradient(135deg, #0c4a6e, #082f49)',
  },
  {
    id: 'prod-08',
    name: 'Loa Bluetooth Marshall Emberton II 360° Sound',
    price: 4150000,
    originalPrice: 4790000,
    category: 'Âm thanh',
    description: 'Âm thanh đa hướng True Stereophonic 360°, thời lượng pin hơn 30 giờ, chuẩn kháng nước bụi IP67 bền bỉ di chuyển.',
    specs: ['Âm thanh 360° đa hướng', 'Pin > 30 giờ chơi nhạc', 'Kháng nước bụi IP67', 'Chế độ Stack Mode ghép đôi'],
    stock: 9,
    rating: 4.9,
    reviewsCount: 118,
    imageColor: 'linear-gradient(135deg, #78350f, #451a03)',
    badge: 'Âm Thanh Đỉnh',
  },
];
